# NOTE: Replace base64 values before applying.
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-secret
  namespace: databases
  labels:
    app.kubernetes.io/name: elasticsearch
    app.kubernetes.io/part-of: kubiquest
    app.kubernetes.io/managed-by: kubectl
type: Opaque
data:
  # echo -n "elastic" | base64
  elasticsearch-username: ZWxhc3RpYw==
  # echo -n "kubipassword" | base64
  elasticsearch-password: a3ViaXBhc3N3b3Jk
