# NOTE: Replace base64 values before applying.
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: databases
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/part-of: kubiquest
    app.kubernetes.io/managed-by: kubectl
type: Opaque
data:
  # echo -n "kubiuser" | base64
  rabbitmq-username: a3ViaXVzZXI=
  # echo -n "kubipassword" | base64
  rabbitmq-password: a3ViaXBhc3N3b3Jk
  # echo -n "kubipassword" | base64  (used by bitnami chart)
  rabbitmq-erlang-cookie: a3ViaXBhc3N3b3Jk
