apiVersion: v1
kind: ServiceAccount
metadata:
  name: developer-user
  namespace: app
  labels:
    app.kubernetes.io/part-of: kubiquest
    app.kubernetes.io/managed-by: kubectl
---
apiVersion: v1
kind: Secret
metadata:
  name: developer-user-token
  namespace: app
  annotations:
    kubernetes.io/service-account.name: developer-user
  labels:
    app.kubernetes.io/part-of: kubiquest
type: kubernetes.io/service-account-token
