apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sysadmin-binding
  labels:
    app.kubernetes.io/part-of: kubiquest
    app.kubernetes.io/managed-by: kubectl
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sysadmin
subjects:
  - kind: ServiceAccount
    name: sysadmin-user
    namespace: kube-system
