apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app

resources:
  - namespace.yaml
  - deployment-frontend.yaml
  - deployment-api.yaml
  - deployment-indexer.yaml
  - cronjob-reporting.yaml
  - service-frontend.yaml
  - service-api.yaml
