{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "indexer.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "indexer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port | default 3000 }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "indexer.selectorLabels" . | nindent 4 }}
{{- end }}
