apiVersion: v2
name: frontend
description: KubiQuest Angular frontend application
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - kubiquest
  - frontend
  - angular
maintainers:
  - name: KubiQuest
