apiVersion: v2
name: api
description: KubiQuest Laravel API application
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - kubiquest
  - api
  - laravel
maintainers:
  - name: KubiQuest
