apiVersion: v1
kind: Service
metadata:
  name: cadvisor
  namespace: monitoring
  labels:
    app.kubernetes.io/name: cadvisor
    app.kubernetes.io/part-of: kubiquest
spec:
  selector:
    app.kubernetes.io/name: cadvisor
  clusterIP: None   # Headless â€” un endpoint par noeud
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
