apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: app
  labels:
    app.kubernetes.io/part-of: kubiquest
    app.kubernetes.io/managed-by: kubectl
spec:
  limits:
    - type: Container
      default:
        memory: 256Mi
        cpu: 200m
      defaultRequest:
        memory: 128Mi
        cpu: 100m
      max:
        memory: 1Gi
        cpu: 1000m
