apiVersion: v1
kind: ResourceQuota
metadata:
  name: app-quota
  namespace: app
  labels:
    app.kubernetes.io/part-of: kubiquest
    app.kubernetes.io/managed-by: kubectl
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 4Gi
    limits.cpu: "8"
    limits.memory: 8Gi
    pods: "20"
    secrets: "20"
    configmaps: "20"
