apiVersion: v2
name: reporting
description: KubiQuest Go daily reporting CronJob
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - kubiquest
  - reporting
  - go
maintainers:
  - name: KubiQuest
